spring:
    application:
        name: Tarlac Virtual Tour
    jpa:
        hibernate:
            ddl-auto: create-drop
    http:
        multipart:
            max-file-size: 50MB
            max-request-size: 1000MB
logging:
    level:
        ph.edu.tsu.tour: TRACE
# Properties related to disk storage.
storage:
    # The default base directory where files are to be saved at.
    # Supported schemes are: "dropbox" and "file" (not recommended).
    base-uri: dropbox:///
    # Dropbox storage configuration.
    dropbox:
        access-token: E95Ro-m6k8AAAAAAAAAADZRS4lBiZeXN6q5BGBsF6KyayvKhhJIc5uNATEUkAT3-
application:
    # Configuration for images.
    image:
        # Indicates if image should be resized. Possible values: "true" and "false".
        resize: false
        # The max width of an image in pixels. If resize is set to true, then this field should be specified.
        # Otherwise, it's optional.
        max-width:
        # The max height of an image in pixels. If resize is set to true, then this field should be specified.
        # Otherwise, it's optional.
        max-height:
        # The quality of the image. Input should range from 0 to 1, with 1 having the most optimal quality.
        quality:
        # Configuration for preview image.
        preview:
            # Indicates if preview image should be resized. Possible values: "true" and "false".
            resize: true
            # The max width of a preview image in pixels. If resize is set to true, then this field should be specified.
            # Otherwise, it's optional.
            max-width: 350
            # The max height of a preview image in pixels. If resize is set to true, then this field should be
            # specified. Otherwise, it's optional.
            max-height: 250
            # The quality of the preview image. Input should range from 0 to 1, with 1 having the most optimal quality.
            quality:
---
spring:
    profiles: production
    datasource:
        url: jdbc:mysql://localhost:3306/my-virtual-tour
        username: root
        password: